    MODULE PRSIZES
        INTEGER, PARAMETER :: ISIZE=SELECTED_INT_KIND(8)
        INTEGER, PARAMETER :: DPSIZE=SELECTED_REAL_KIND(8)
        INTEGER, PARAMETER :: PE=6
        INTEGER, PARAMETER :: PC=30
        INTEGER, PARAMETER :: PCT=30
        INTEGER, PARAMETER :: PIR=700
        INTEGER, PARAMETER :: PD=9
        INTEGER, PARAMETER :: PAL=50
        INTEGER, PARAMETER :: MAXFCN=1000000
        INTEGER, PARAMETER :: PG=PCT+50
    END MODULE PRSIZES
